[package]
name = "rote"
version = "0.2.2"
authors = ["Ryan1729 <Ryan1729@gmail.com>"]
license = "MIT and Apache 2.0"

[dependencies]

[dependencies.platform_layer]
path = "./libs/platform_layer"

[dev-dependencies]
quickcheck = "0.4"
rand = "0.3"
